name: mes_tchams
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1
  diacritic: ^0.1.5
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/icons/
    - assets/images/
  fonts: 
    - family : Kaushan Script
      fonts :
        - asset : assets/fonts/KaushanScript-Regular.ttf
    
